<?php
/**
 * Contact page
 * 
 * @var Zcmf\Content\Model\Text $text
 * @var Zcmf\Content\Model\Form $form
 */
?>

<? if (isset($messages)):?>
<aside>
    <ul>
    <? foreach ($messages as $message):?>
        <li><?= $message?></li>
    <? endforeach?>
    </ul>
</aside>
<? endif?>

<article>
    <?= $this->renderForm($form, $current_route)?>
    <?= $this->renderText($text)?>
</article>